<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="SoapIntegrationService" targetNamespace="http://SoapIntegrationService" xmlns:bons1="http://www.example.org/TestSoapIntegration" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://SoapIntegrationService" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="SoapIntegrationServiceHttpBinding" originalBindingStyle="document"/>
        <generatedXSD location="SoapIntegrationService_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  
  
  <wsdl:types>
    
        <xsd:schema targetNamespace="http://SoapIntegrationService" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
            <xsd:import namespace="http://www.example.org/TestSoapIntegration" schemaLocation="TestSoapIntegration.xsd"/>
            <xsd:include schemaLocation="SoapIntegrationService_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="getEmployeeDetailsRequestMsg">
    <wsdl:part element="tns:getEmployeeDetails" name="getEmployeeDetailsParameters"/>
  </wsdl:message>
  <wsdl:message name="getEmployeeDetailsResponseMsg">
    <wsdl:part element="tns:getEmployeeDetailsResponse" name="getEmployeeDetailsResult"/>
  </wsdl:message>
  <wsdl:portType name="SoapIntegrationService">
    <wsdl:operation name="getEmployeeDetails">
      <wsdl:input message="tns:getEmployeeDetailsRequestMsg" name="getEmployeeDetailsRequest"/>
      <wsdl:output message="tns:getEmployeeDetailsResponseMsg" name="getEmployeeDetailsResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SoapIntegrationServiceHttpBinding" type="tns:SoapIntegrationService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getEmployeeDetails">
      <soap:operation soapAction="http://SoapIntegrationService/getEmployeeDetails"/>
      <wsdl:input name="getEmployeeDetailsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getEmployeeDetailsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="SoapIntegrationServiceHttpService">
    <wsdl:port binding="tns:SoapIntegrationServiceHttpBinding" name="SoapIntegrationServiceHttpPort">
      <soap:address location="http://localhost:7800/SoapIntegrationService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>